feat: Add "rentedDay" and "periodChosen" columns
decentraland/signatures-server pull request #165
Opened 2022-11-07 15:02 UTC by juanmahidalgo

Closes #163
Closes #164

2022-11-07 20:43 UTC, LautaroPetaccio requested changes

2022-11-07 20:43 UTC, LautaroPetaccio commented on src/migrations/1667818838202_add-rentedDays-and-periodChosen-columns.ts
> +const rentedDaysColumn = "rentedDays"
We're using snake case for the columns and tables, would you mind changing it?
```suggestion
const rentedDaysColumn = "rented_days"
```

2022-11-07 20:43 UTC, LautaroPetaccio commented on src/ports/rentals/component.ts
> +      FROM rentals JOIN periods p on p.rental_id = rentals.id, metadata, rentals_listings
Was there a requirement to use the `JOIN` keyword? The keyword seems to have divided the clauses that were being used to join the tables, `metadata.id = rentals.metadata_id` was left on the WHERE clause and is part of the JOIN.

2022-11-07 20:43 UTC, LautaroPetaccio commented on src/ports/rentals/component.ts
> +            const dbRental = dbRentals.find(({ max_days }) => max_days === Number(rental.rentalDays)) || dbRentals[0]
Is this used to find a `dbRental` from all the possible dbRentals? There can't be more than one dbRental with the same signature, so this shouldn't happen.

2022-11-08 11:18 UTC, juanmahidalgo commented on src/migrations/1667818838202_add-rentedDays-and-periodChosen-columns.ts
> +const rentedDaysColumn = "rentedDays"
Updated!

2022-11-08 11:47 UTC, juanmahidalgo commented on src/ports/rentals/component.ts
> +      FROM rentals JOIN periods p on p.rental_id = rentals.id, metadata, rentals_listings
Not sure I'm following the requested change here, I think the query was working as expected, the `WHERE` was not changed, I just added an _explicit_ `JOIN`. I changed to an _implicit_ one to keep the same approach as the other ones.

2022-11-08 11:49 UTC, juanmahidalgo commented on src/ports/rentals/component.ts
> +            const dbRental = dbRentals.find(({ max_days }) => max_days === Number(rental.rentalDays)) || dbRentals[0]
The query now that is joining by period, will return several rows and so we need to know which period corresponds with the `rentalDays`

2022-11-08 13:06 UTC, LautaroPetaccio commented on src/ports/rentals/component.ts
> +                  )}, rented_days = ${rental.rentalDays}, period_chosen = ${
Not needed.

2022-11-08 13:06 UTC, LautaroPetaccio commented on src/ports/rentals/component.ts
> +          }, rented_days = ${indexerRentals[0].rentalDays}, period_chosen = ${
Not needed.

2022-11-08 13:06 UTC, LautaroPetaccio approved these changes

2022-11-08 13:15 UTC, merged