feat: Refresh rentals listings endpoint
decentraland/signatures-server pull request #34
Opened 2022-07-13 17:27 UTC by LautaroPetaccio

This PR adds the refresh rentals endpoint to refresh the rental listings when the user uses the signature to perform a rental.
Closes #11

2022-07-13 18:03 UTC, fzavalia requested changes
Good job!
Added some comments to be reviewed.

2022-07-14 13:23 UTC, LautaroPetaccio commented on src/ports/rentals/component.ts
> +    const blockChainRental = await getBlockchainRentals({
Changed it.

2022-07-14 13:23 UTC, LautaroPetaccio commented on src/ports/rentals/component.ts
> +      queryVariables += Object.entries(options.filterBy).reduce((acc, [key, value]) => {
The join is definitely better, I'll change it.

2022-07-14 13:23 UTC, LautaroPetaccio commented on src/ports/rentals/component.ts
> +      querySignature += `firsts: ${options.firsts} `
It's first as you said, changing it.

2022-07-14 13:24 UTC, LautaroPetaccio commented on src/controllers/handlers/rentals-handlers.ts
> +    } else if (error instanceof NFTNotFound) {
That would work if there wasn't a throw at the end. The idea is to match any of those errors and, if not, throw the error again so it bubbles up.

2022-07-14 13:24 UTC, LautaroPetaccio commented on src/components.ts
> +  console.log("Marketplace subgraph url", MARKETPLACE_SUBGRAPH_URL)
It's not! Removed it

2022-07-14 13:27 UTC, fzavalia commented on src/controllers/handlers/rentals-handlers.ts
> +    } else if (error instanceof NFTNotFound) {
```
if (RentalNotFound) {
  return
}

if (NFTNotFound) {
  return
}

throw
```

2022-07-14 14:14 UTC, LautaroPetaccio commented on test/unit/rentals-component.spec.ts
> +    describe("and it was updated before or equal the one in the database", () => {
Splitted into two tests!

2022-07-14 14:21 UTC, fzavalia requested changes
Just one more thing

2022-07-14 14:21 UTC, fzavalia commented on src/ports/rentals/component.ts
> +    const indexerRental = await getRentalsFromIndexer({
I would name this `indexerRentals` as it is an array

2022-07-14 14:24 UTC, fzavalia approved these changes

2022-07-14 14:27 UTC, merged